## Matrix_Manipulation

In [2]:
import torch

#### Matrix Multiplication

In [3]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


#### Multiplication -  element-wise
동일한 크기의 행렬이 동일한 위치에 있는 원소끼리 곱하는 것

In [5]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


#### 평균(Mean)

In [6]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [13]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())
print(t.mean(dim=0)) # 첫번째 차원을 제거한다. (2, 2)의 크기에서 (1, 2)의 크기로 변경
print(t.mean(dim=1)) # 두번째 차원을 제거합니다. (2, 2)의 크기에서 (2, 1)의 크기로 변경
print(t.mean(dim=-1)) # 마지막 차원을 제거한다는 의미이고, 결국 열의 차원을 제거한다는 의미와 같습니다.

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


#### 덧셈(Sum)

In [14]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


#### 최대(Max)와 아그맥스(ArgMax)
max에 dim 인자를 주면 argmax도 함께 리턴하는 특징 때문입니다.

In [15]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.max()) # Returns one value: max
print(t.max(dim=0)) # Returns two values: max and argmax
print(t.max(dim=1))
print(t.max(dim=-1))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
