#### Tensor create with Numpy

In [2]:
import numpy as np
import torch
import torch.nn.functional as F

torch.manual_seed(1)

In [5]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print('Type of t:', type(t))
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Type of t: <class 'numpy.ndarray'>
Rank of t:  1
Shape of t:  (7,)


In [6]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print('Type of t:', type(t))
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Type of t: <class 'numpy.ndarray'>
Rank  of t:  2
Shape of t:  (4, 3)


#### PyTorch Tensor Allocation

In [9]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(type(t))
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

<class 'torch.Tensor'>
1
torch.Size([7])
torch.Size([7])


In [10]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(type(t))
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

<class 'torch.Tensor'>
2
torch.Size([4, 3])
torch.Size([4, 3])


#### 차원 변경
파이토치 텐서의 뷰(View)는 넘파이에서의 리쉐이프(Reshape)와 같은 역할을 합니다.

In [17]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [18]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


#### 스퀴즈(Squeeze) - 1인 차원을 제거한다.

In [15]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [16]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


#### 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다.

In [7]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

torch.Size([3])
tensor([0., 1., 2.])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([0., 1., 2.])


In [21]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [22]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [23]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


#### 타입 캐스팅(Type Casting)

In [24]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float()) # float type 변화


tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


#### 두 테서 연결하기(concatenate)

In [28]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0)) # 두 개의 (2 × 2) 텐서가 (4 × 2) 
print(torch.cat([x, y], dim=1)) # 두 개의 (2 × 2) 텐서가 (2 × 4) 

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


#### 스택킹(Stacking)

In [31]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=0))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


#### ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서

In [32]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [34]:
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### In-place Operation (덮어쓰기 연산)

In [35]:
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[0., 2., 4.],
        [4., 2., 0.]])
tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [37]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x)  # 기존의 값 출력

tensor([[0., 2., 4.],
        [4., 2., 0.]])
tensor([[0., 2., 4.],
        [4., 2., 0.]])


#### Scatter
scatter의 첫번째 인자로 dim=1에 대해서 수행하라고 알려주고, 세번째 인자에 숫자 1을 넣어주므로서 두번째 인자인 y_unsqeeze(1)이 알려주는 위치에 숫자 1을 넣도록 합니다. 

In [16]:
z = torch.rand(3, 5, requires_grad=True)
y = torch.randint(5, (3,)).long()
hypothesis = F.softmax(z, dim=1)
y_one_hot = torch.zeros_like(hypothesis) 
y_one_hot.scatter_(1, y.unsqueeze(1), 1)

tensor([[0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

#### Torch random

In [10]:
torch.rand(3, 5, requires_grad=True)

tensor([[0.7576, 0.2793, 0.4031, 0.7347, 0.0293],
        [0.7999, 0.3971, 0.7544, 0.5695, 0.4388],
        [0.6387, 0.5247, 0.6826, 0.3051, 0.4635]], requires_grad=True)

In [11]:
torch.randn(3, 5, requires_grad=True)

tensor([[-1.8349, -2.2149,  0.0436,  1.3240, -0.1005],
        [ 0.6443,  0.5244,  1.0157,  0.2571, -0.9013],
        [ 0.8138,  0.3871,  0.5417,  0.6646,  0.3248]], requires_grad=True)

In [12]:
torch.randint(5, (3,)).long()

tensor([4, 1, 4])

## optimizer.zero_grad()가 필요한 이유
파이토치는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적시키는 특징이 있습니다. 예를 들어봅시다.

In [3]:
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

  z = 2*w

  z.backward()
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


## 자동 미분(Autograd) 실습하기

In [4]:
w = torch.tensor(2.0, requires_grad=True)
y = w**2
z = 2*y + 5

print(z)

z.backward()
print('수식을 w로 미분한 값 : {}'.format(w.grad))

tensor(13., grad_fn=<AddBackward0>)
수식을 w로 미분한 값 : 8.0
